runtime: php72

handlers:
  - url: /(.*\.(gif|png|jpg|css|js))$
    static_files: public/\1
    upload: public/.*\.(gif|png|jpg|css|js)$

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:cMV2Z8UTxm6BU26HyIaFoVee2H8LWHm4GTooSgvOsys=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie
