service: demo-laravel-aws

provider:
    name: aws
    region: us-east-1
    runtime: provided
    environment:
        APP_ENV: dev
        APP_DEBUG: true
        LOG_CHANNEL: stderr
        SESSION_DRIVER: cookie
        VIEW_COMPILED_PATH: /tmp/storage/framework/views
        APP_STORAGE: /tmp

plugins:
    - ./vendor/bref/bref

functions:
    website:
        handler: public/index.php
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-74-fpm}
        events:
            - http: 'ANY /'
            - http: 'ANY /{proxy+}'
    artisan:
        handler: artisan
        timeout: 120 # in seconds
        layers:
            - ${bref:layer.php-74} # PHP
            - ${bref:layer.console} # The "console" layer

package:
    exclude:
        - node_modules/**
        - public/storage
        - resources/assets/**
        - storage/**
        - tests/**
